# GBasis Tutorial

This tutorial demonstrates various functionalities of `gbasis`, a free and open-source Python library to facilitate the use of Gaussian basis functions in molecular quantum chemistry.

# Table of Contents  
- [1 Basis Sets](#1-Basis-Sets)
    - [1.1 Loading Basis Sets](#1.1-Loading-Basis-Sets)
    - [1.2 Building Basis Sets](#1.2-Building-Basis-Sets)
    - [1.3 Types of Coordinate Systems Used by Basis Functions](#1.3-Types-of-Coordinate-Systems-Used-by-Basis-Functions)
    - [1.4 Linear Transformations of Basis Functions](#1.4-Linear-Transformations-of-Basis-Functions)
- [2 Evaluations](#2-Evaluations)
    - [2.1 Evaluation of Contractions](#2.1-Evaluation-of-Contractions)
    - [2.2 Evaluation of Derivatives of Contractions](#2.2-Evaluation-of-Derivatives-of-Contractions)
    - [2.3 Evaluations of Density Related Properties](#2.3-Evaluations-of-Density-Related-Properties)
        - [2.3.1 Density](#2.3.1-Density)
        - [2.3.2 Arbitrary Derivatives of Density](#2.3.2-Arbitrary-Derivatives-of-Density)
        - [2.3.3 Gradient of Density](#2.3.3-Gradient-of-Density)
        - [2.3.4 Laplacian of Density](#2.3.4-Laplacian-of-Density)
        - [2.3.5 Hessian of Density](#2.3.5-Hessian-of-Density)
    - [2.4 Evaluations of Density Matrix Related Properties](#2.4-Evaluations-of-Density-Matrix-Related-Properties)
        - [2.4.1 Stress Tensor](#2.4.1-Stress-Tensor)
        - [2.4.2 Ehrenfest Force](#2.4.2-Ehrenfest-Force)
        - [2.4.3 Ehrenfest Hessian](#2.4.3-Ehrenfest-Hessian)
        - [2.4.4 Positive-Definite Kinetic Energy Density](#2.4.4-Positive-Definite-Kinetic-Energy-Density)
        - [2.4.5 General Form of Kinetic Energy Density](#2.4.5-General-Form-of-Kinetic-Energy-Density)
- [3 Integrals](#3-Integrals)
    - [3.1 Overlap Integral](#3.1-Overlap-Integral)
        - [3.1.1 Overlap Integral Between Two Different Basis Sets](#3.1.1-Overlap-Integral-Between-Two-Different-Basis-Sets)
    - [3.2 Multipole Moment Integral](#3.2-Multipole-Moment-Integral)
    - [3.3 Integrals Over Differential Operator](#3.3-Integrals-Over-Differential-Operator)
        - [3.3.1 Kinetic Energy Integral](#3.3.1-Kinetic-Energy-Integral)
        - [3.3.2 Momentum Integral](#3.3.2-Momentum-Integral)
        - [3.3.3 Angular Momentum Integral](#3.3.3-Angular-Momentum-Integral)
    - [3.4 Integral for Interaction with Point Charge](#3.4-Integral-for-Interaction-with-Point-Charge)
        - [3.4.1 Nuclear-Electron Attraction Integral](#3.4.1-Nuclear-Electron-Attraction-Integral)
        - [3.4.2 Electrostatic Potential](#3.4.2-Electrostatic-Potential)
    - [3.5 Electron-Electron Repulsion Integral](#3.5-Electron-Electron-Repulsion-Integral)

In the examples in the [Evaluations](#2-Evaluations) and [Integrals](#3-Integrals) sections, we will ubiquitously make use of global variables that are defined in the code cell below. These examples will generally use a Krypton atom as the system of study (note that [Section 3.1.1](#3.1.1-Overlap-Integral-Between-Two-Different-Basis-Sets) uses its own, separate example), represented with the STO-6G basis set (`basis`). The STO-6G basis set assigns 18 basis functions (atomic orbitals, AOs) to Krypton. We define an arbitrary transformation matrix (`transform`) that can be used to obtain 14 molecular orbitals (MOs) from these 18 atomic orbitals. Separate one-electron density matrices expressed with respect to the AOs and MOs are generated randomly. Also, we randomly select Cartesian coordinates to represent rudimentary grids for showcasing functions in the `gbasis.evals` modules. After most code blocks, outputs of calculations, shapes of said outputs, or other clarifying information will be provided to justify that things work properly.

P.S. Don't worry if you don't know how to use the `gbasis` functionality implemented in this cell - it should be clarified shortly in [Section 1.1](#1.1-Loading-Basis-Sets).

In [1]:
import gbasis
import numpy as np
from gbasis.parsers import parse_nwchem, make_contractions

# create an STO-6G basis in spherical coordinates for Kr (18 basis functions total)
basis_dict = parse_nwchem("data_sto6g.nwchem")
basis = make_contractions(basis_dict, ["Kr"], np.array([[0, 0, 0]]), coord_types="spherical")

# define a tranformation matrix to obtain 14 molecular orbitals from 18 atomic orbitals
transform = np.random.rand(14, 18)

# the following represents a one-electron density matrix expressed w.r.t. atomic orbitals
one_dm_atomic = np.random.rand(18, 18)
one_dm_atomic += one_dm_atomic.T

# the following represents the one-electron density matrix expressed w.r.t. molecular orbitals
one_dm_molecular = np.random.rand(14, 14)
one_dm_molecular += one_dm_molecular.T

# define Cartesian coordinates of points in space (in atomic units) where basis functions are evaluated
one_point = np.random.rand(1, 3)
ten_points = np.random.rand(10, 3)

# 1 Basis Sets

In `gbasis`, a basis set is defined to be a list of shells of generalized contractions (i.e., a list of `GeneralizedContractionShell` objects).

## 1.1 Loading Basis Sets

Basis set information is often stored in text format. In `gbasis`, the Gaussian94 format (.gbs) and
the NWChem format (.nw) are supported.

In [2]:
from gbasis.parsers import parse_gbs, parse_nwchem, make_contractions

# use H2 molecule as an example system
atoms = ["H", "H"]
coords = np.array([[0, 0, 0], [0, 0, 1]])

# load hydrogen def2-SVP basis set information with the Gaussian94 format
gbs_basis_dict = parse_gbs("hydrogen_def2-svp.1.gbs")
gbs_basis = make_contractions(gbs_basis_dict, atoms, coords)

# load hydrogen def2-SVP basis set information with the NWChem format
nw_basis_dict = parse_nwchem("hydrogen_def2-svp.1.nw")
nw_basis = make_contractions(nw_basis_dict, atoms, coords)

# print gbs_basis_dict and nw_basis_dict to verify they are the same
print("def2-SVP Basis Set Loaded from Gaussian94 Format:")
print(gbs_basis_dict)
print()
print("def2-SVP Basis Set Loaded from NWChem Format:")
print(nw_basis_dict)

def2-SVP Basis Set Loaded from Gaussian94 Format:
{'H': [(0, array([13.010701  ,  1.9622572 ,  0.44453796]), array([[0.01968216],
       [0.13796524],
       [0.47831935]])), (0, array([0.12194962]), array([[1.]])), (1, array([0.8]), array([[1.]]))]}

def2-SVP Basis Set Loaded from NWChem Format:
{'H': [(0, array([13.010701  ,  1.9622572 ,  0.44453796]), array([[0.01968216],
       [0.13796524],
       [0.47831935]])), (0, array([0.12194962]), array([[1.]])), (1, array([0.8]), array([[1.]]))]}


## 1.2 Building Basis Sets

`gbasis` interfaces to the `iodata` module, which handles the inputs and outputs for different quantum chemistry formats, such as Gaussian formatted checkpoint files (.fchk) and AIM
wavefunction files (.wfn and .wfx). Additonally, `gbasis` interfaces to `pyscf`, which is an ab initio computational chemistry program.

In [3]:
from iodata import load_one
from pyscf import gto
from gbasis.wrappers import from_iodata, from_pyscf

# build a basis from an fchk file (water at uwB97XD/def2-TZVPD LOT) using IOData
iodata_mol = load_one("water.fchk")
iodata_basis = from_iodata(iodata_mol)

# build an STO-3G basis for water using PySCF
pyscf_mol = gto.Mole()
pyscf_mol.build(
    atom = "O 0 0 0; H 0 1 0; H 0 0 1",
    basis = "sto-3g"
)
pyscf_basis = from_pyscf(pyscf_mol)

## 1.3 Types of Coordinate Systems Used by Basis Functions

In `gbasis`, the user can provide the coordinate system used by each shell of generalized contractions that gets stored in the basis list. The `make_contractions` function is useful for instantiating a basis for a system of atoms based on the `basis_dict` output of the parsers from `gbasis.parsers`. For a given call of `make_contractions`, one can pass either a string ("cartesian" or "spherical") or a list of strings to specify `coord_types`. If a string is passed, all contractions for all atoms are treated as having the same `coord_type`. 
If different shells correspond to different coordinate systems, then a list of the same length as the basis must be provided with each entry being "spherical" or "cartesian" to specify the coordinate system
of the corresponding shell. For example, if atom 1 contributes 8 contractions and atom 2 contributes 8 contractions, the `coord_types` list should be of length 16, where the first 8 elements correspond to contractions for atom 1 and the last 8 elements correspond to contractions for atom 2. These possibilities are illustrated in the code cell below using the Kr<sub>2</sub> molecule as an example:

In [4]:
# load STO-6G basis set information
basis_dict = parse_nwchem("data_sto6g.nwchem")

# create basis for Kr2 using cartesian coordinates for all generalized contractions
cartesian_basis = make_contractions(basis_dict, 
                                    ["Kr", "Kr"], 
                                    np.array([[0, 0, 0], [1, 0, 0]]),
                                    coord_types="cartesian")
print([shell.coord_type for shell in cartesian_basis])
print()

# create basis for Kr2 using spherical coordinates for all generalized contractions
spherical_basis = make_contractions(basis_dict, 
                                    ["Kr", "Kr"], 
                                    np.array([[0, 0, 0], [1, 0, 0]]),
                                    coord_types="spherical")
print([shell.coord_type for shell in spherical_basis])
print()

# create basis for Kr2 using spherical coordinates for all generalized contractions
# except the last one, which is specified to be cartesian
mixed_basis = make_contractions(basis_dict, 
                                ["Kr", "Kr"], 
                                np.array([[0, 0, 0], [1, 0, 0]]),
                                coord_types=["spherical"] * 15 + ["cartesian"])
print([shell.coord_type for shell in mixed_basis])

['cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian', 'cartesian']

['spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical']

['spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'spherical', 'cartesian']


## 1.4 Linear Transformations of Basis Functions

In `gbasis`, the user can linearly transform the basis functions before computing the desired properties.
All of the higher level functions have the keyword argument `transform` to specify the matrix that
transforms the basis set. The transformation is applied to the left, i.e.,

$$\begin{equation}
 \psi_i = \sum_j T_{ij} \phi_j
\end{equation}$$

where {$\phi_{j}$} is the basis set before transformation and {$\psi_{i}$} is the basis function after transformation.
The number of basis functions depends on the coordinate systems specified for each shell. 

Examples involving such transformations will be provided subsequently in this notebook wherever molecular rather than atomic orbitals are involved in calculations.

# 2 Evaluations

## 2.1 Evaluation of Contractions

The functions in the module `gbasis.evals.eval` return the evaluations of the contractions at different
coordinates:

$$\begin{equation}
  \phi(\mathbf{r}_n | \mathbf{R}_{A}, \mathbf{a}_j, \mathbf{d}_k, \boldsymbol{\alpha})
\end{equation}$$

The returned value is an array whose rows corresponds to the basis function and columns corresponds to the coordinate, $\mathbf{r}_n$.These functions can be used to find the values of the orbitals at various points, such as a grid.

In [5]:
from gbasis.evals.eval import evaluate_basis

# evalute atomic orbitals at a ten points
atomic_orb_evaluation = evaluate_basis(basis, ten_points)

# evaluate molecular orbitals at ten points
molecular_orb_evaluation = evaluate_basis(basis, ten_points, transform)

# verify shapes of evaluations
print("Shape of Atomic Orbital Evaluation (Number of AOs, Number of Evaluation Points):")
print(atomic_orb_evaluation.shape)
print()
print("Shape of Molecular Orbital Evaluation (Number of MOs, Number of Evaluation Points):")
print(molecular_orb_evaluation.shape)

Shape of Atomic Orbital Evaluation (Number of AOs, Number of Evaluation Points):
(18, 10)

Shape of Molecular Orbital Evaluation (Number of MOs, Number of Evaluation Points):
(14, 10)


## 2.2 Evaluation of Derivatives of Contractions

In `gbasis`, contractions can be derivatized to arbitrary orders. The functions in module `gbasis.evals.eval_deriv`
return the evaluations of the given derivative of the contractions at different coordinates.

$$\begin{equation}
  \frac{\partial^{m_x + m_y + m_z}}{\partial x^{m_x} \partial y^{m_y} \partial z^{m_z}}
  \phi(\mathbf{r}_n | \mathbf{R}_{A}, \mathbf{a}_j, \mathbf{d}_k, \boldsymbol{\alpha})
\end{equation}$$

The returned value is an array whose rows corresponds to the basis function and columns corresponds to the coordinate, $\mathbf{r}_n$.

In the example code cell below, presume the following derivative of the contraction is desired:

$$\frac{\partial ^{3}}{\partial x \partial y^{2}}$$

In [6]:
from gbasis.evals.eval_deriv import evaluate_deriv_basis

# evaluate the derivatives of the atomic orbitals at ten points
atomic_basis_deriv = evaluate_deriv_basis(basis, ten_points, np.array([1, 2, 0]))

# evaluate the derivatives of the molecular orbitals at ten points
molecular_basis_deriv = evaluate_deriv_basis(basis, ten_points, np.array([1, 2, 0]), transform)

# verify shapes of derivative evaluations
print("Shape of Atomic Orbital Derivative Evaluation (Number of AOs, Number of Evaluation Points):")
print(atomic_basis_deriv.shape)
print()
print("Shape of Molecular Orbital Derivative Evaluation (Number of MOs, Number of Evaluation Points):")
print(molecular_basis_deriv.shape)

Shape of Atomic Orbital Derivative Evaluation (Number of AOs, Number of Evaluation Points):
(18, 10)

Shape of Molecular Orbital Derivative Evaluation (Number of MOs, Number of Evaluation Points):
(14, 10)


## 2.3 Evaluations of Density Related Properties

The functions in the module `gbasis.evals.density` return the evaluations of the
density and its derivatives. Note that the examples below are not to be taken literally. The one-electron density matrices, expressed with respect to either atomic or molecular orbitals, were separately generated via `np.random.rand` and thus have no connection to one another. This method is not a bona fide way of approaching things.

### 2.3.1 Density

$$\rho(\mathbf{r}_n) = \sum_{ij} \gamma_{ij} \phi_i(\mathbf{r}_n) \phi_j(\mathbf{r}_n)$$

In [7]:
from gbasis.evals.density import evaluate_density

# evaluate the density at ten points using the density matrix expressed w.r.t. atomic orbitals
atomic_basis_density = evaluate_density(one_dm_atomic, basis, ten_points)

# evaluate the density at ten points using the density matrix expressed w.r.t. molecular orbitals
molecular_basis_density = evaluate_density(one_dm_molecular, basis, ten_points, transform)

print("Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(atomic_basis_density)
print()
print("Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(molecular_basis_density)

Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[17.48775026  3.405866    1.02884483  0.747302    0.87205537  1.02569778
  1.03041191 17.69236884  1.55916371  1.05981276]

Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[828.73212551 174.4626635   31.58990189  43.1199123   45.78803695
  54.72789327  56.87535499 775.14650396  72.95468064  59.29519656]


### 2.3.2 Arbitrary Derivatives of Density

$$\frac{\partial^{L_x + L_y + L_z}}{\partial x^{L_x} \partial y^{L_y} \partial z^{L_z}}
  \rho(\mathbf{r}_n)
  =
  \sum_{l_x=0}^{L_x} \sum_{l_y=0}^{L_y} \sum_{l_z=0}^{L_z}
  \binom{L_x}{l_x} \binom{L_y}{l_y} \binom{L_z}{l_z}
  \sum_{ij} \gamma_{ij}
  \frac{\partial^{l_x + l_y + l_z} \rho(\mathbf{r}_n)}{\partial x^{l_x} \partial y^{l_y} \partial z^{l_z}}
  \frac{
    \partial^{L_x + L_y + L_z - l_x - l_y - l_z} \rho(\mathbf{r}_n)
  }{
    \partial x^{L_x - l_x} \partial y^{L_y - l_y} \partial z^{L_z - l_z}
  }$$
  
In the example code cell below, presume the following derivative of the density is desired:

$$\frac{\partial ^{3}}{\partial x \partial y^{2}}$$

In [8]:
from gbasis.evals.density import evaluate_deriv_density

# evaluate the derivative of density at one point using the density matrix expressed w.r.t. atomic orbitals
atomic_basis_density_deriv = evaluate_deriv_density(np.array([1, 2, 0]), one_dm_atomic, basis, one_point)

# evaluate the derivative of density at one point using the density matrix expressed w.r.t. molecular orbitals
molecular_basis_density_deriv = evaluate_deriv_density(np.array([1, 2, 0]), 
                                                       one_dm_molecular, 
                                                       basis, 
                                                       one_point, 
                                                       transform)

print("Derivative of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(atomic_basis_density_deriv)
print()
print("Derivative of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(molecular_basis_density_deriv)

Derivative of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[-46.84255675]

Derivative of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[-3352.52476766]


### 2.3.3 Gradient of Density

$$
\begin{equation}
  \nabla \rho(\mathbf{r}_n)
  =
  \begin{bmatrix}
    \frac{\partial}{\partial x} \rho(\mathbf{r}_n)\\\\
    \frac{\partial}{\partial y} \rho(\mathbf{r}_n)\\\\
    \frac{\partial}{\partial z} \rho(\mathbf{r}_n)
  \end{bmatrix}\\
\end{equation}
$$

In [9]:
from gbasis.evals.density import evaluate_density_gradient

# evaluate the gradient of density at one point using the density matrix expressed w.r.t. atomic orbitals
atomic_basis_density_grad = evaluate_density_gradient(one_dm_atomic, basis, one_point)

# evaluate the gradient of density at one point using the density matrix expressed w.r.t. molecular orbitals
molecular_basis_density_grad = evaluate_density_gradient(one_dm_molecular, basis, one_point, transform)

print("Gradient of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(atomic_basis_density_grad)
print()
print("Gradient of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(molecular_basis_density_grad)

Gradient of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[-3.49799097 -6.12298383 -9.17460362]]

Gradient of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[[-169.20645087 -340.34201305 -462.53015523]]


### 2.3.4 Laplacian of Density

$$
\begin{equation}
  \nabla^2 \rho(\mathbf{r}_n)
  =
  \frac{\partial^2}{\partial x^2} \rho(\mathbf{r}_n)
  + \frac{\partial^2}{\partial y^2} \rho(\mathbf{r}_n)
  + \frac{\partial^2}{\partial z^2} \rho(\mathbf{r}_n)
\end{equation}
$$

In [10]:
from gbasis.evals.density import evaluate_density_laplacian

# evaluate the Laplacian of density at one point using the density matrix expressed w.r.t. atomic orbitals
atomic_basis_density_laplacian = evaluate_density_laplacian(one_dm_atomic, basis, one_point)

# evaluate the Laplacian of density at one point using the density matrix expressed w.r.t. molecular orbitals
molecular_basis_density_laplacian = evaluate_density_laplacian(one_dm_molecular, basis, one_point, transform)

print("Laplacian of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(atomic_basis_density_laplacian)
print()
print("Laplacian of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(molecular_basis_density_laplacian)

Laplacian of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[44.66390972]

Laplacian of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[2153.31390407]


### 2.3.5 Hessian of Density

$$
\begin{equation}
  H[\rho(\mathbf{r}_n)]
  =
  \begin{bmatrix}
    \frac{\partial^2}{\partial x^2} \rho(\mathbf{r}_n) &
    \frac{\partial^2}{\partial x \partial y} \rho(\mathbf{r}_n) &
    \frac{\partial^2}{\partial x \partial z} \rho(\mathbf{r}_n)\\\\
    \frac{\partial^2}{\partial x \partial y} \rho(\mathbf{r}_n) &
    \frac{\partial^2}{\partial y^2} \rho(\mathbf{r}_n)&
    \frac{\partial^2}{\partial y \partial z} \rho(\mathbf{r}_n)\\\\
    \frac{\partial^2}{\partial x \partial z} \rho(\mathbf{r}_n) &
    \frac{\partial^2}{\partial z^2} \rho(\mathbf{r}_n)&
    \frac{\partial^2}{\partial x \partial z} \rho(\mathbf{r}_n)\\
  \end{bmatrix}\\
\end{equation}
$$

In [11]:
from gbasis.evals.density import evaluate_density_hessian

# evaluate the Hessian of density at one point using the density matrix expressed w.r.t. atomic orbitals
atomic_basis_density_hess = evaluate_density_hessian(one_dm_atomic, basis, one_point)

# evaluate the Hessian of density at one point using the density matrix expressed w.r.t. molecular orbitals
molecular_basis_density_hess = evaluate_density_hessian(one_dm_molecular, basis, one_point, transform)

print("Hessian of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(atomic_basis_density_hess)
print()
print("Hessian of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(molecular_basis_density_hess)

Hessian of Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[[-7.59220332 16.80607008 23.540365  ]
  [16.80607008  9.55704853 41.88318099]
  [23.540365   41.88318099 42.6990645 ]]]

Hessian of Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[[[-459.40027881  938.48948801 1147.83720683]
  [ 938.48948801  642.31483023 2225.88407013]
  [1147.83720683 2225.88407013 1970.39935265]]]


## 2.4 Evaluations of Density Matrix Related Properties

Given the density matrix,

$$
\begin{equation}
  \gamma(\mathbf{r}_1, \mathbf{r}_2)
  = \sum_{ij} \gamma_{ij} \phi_i(\mathbf{r}_1) \phi_j(\mathbf{r}_2)
\end{equation}
$$

many properties can be defined by evaluating the derivatives of the density
matrix at the same coordinate:

$$
\begin{equation}
  \left.
    \frac{\partial^{p_x + p_y + p_z}}{\partial x_1^{p_x} \partial y_1^{p_y} \partial z_1^{p_z}}
    \frac{\partial^{q_x + q_y + q_z}}{\partial x_2^{q_x} \partial y_2^{q_y} \partial z_2^{q_z}}
    \gamma(\mathbf{r}_1, \mathbf{r}_2)
  \right|_{\mathbf{r}_1 = \mathbf{r}_2 = \mathbf{r}_n} =
  \sum_{ij} \gamma_{ij}
  \left.
    \frac{\partial^{p_x + p_y + p_z}}{\partial x_1^{p_x} \partial y_1^{p_y} \partial z_1^{p_z}}
    \phi_i(\mathbf{r}_1)
  \right|_{\mathbf{r}_1 = \mathbf{r}_n}
  \left.
    \frac{\partial^{q_x + q_y + q_z}}{\partial x_2^{q_x} \partial y_2^{q_y} \partial z_2^{q_z}}
    \phi_j(\mathbf{r}_2)
  \right|_{\mathbf{r}_1 = \mathbf{r}_n}
\end{equation}
$$

where $\mathbf{r}_1$ is the first coordinate, $\mathbf{r}_2$ is the second
coordinate, and $\mathbf{r}_n$ is the coordinate at which the derivative is
evaluated.

Since $\gamma_{ij}$ is symmetric,

$$
\begin{equation}
  \left.
    \frac{\partial^{p_x + p_y + p_z}}{\partial x_1^{p_x} \partial y_1^{p_y} \partial z_1^{p_z}}
    \frac{\partial^{q_x + q_y + q_z}}{\partial x_2^{q_x} \partial y_2^{q_y} \partial z_2^{q_z}}
    \gamma(\mathbf{r}_1, \mathbf{r}_2)
  \right|_{\mathbf{r}_1 = \mathbf{r}_2 = \mathbf{r}_n} =
  \left.
    \frac{\partial^{q_x + q_y + q_z}}{\partial x_1^{q_x} \partial y_1^{q_y} \partial z_1^{q_z}}
    \frac{\partial^{p_x + p_y + p_z}}{\partial x_2^{p_x} \partial y_2^{p_y} \partial z_2^{p_z}}
    \gamma(\mathbf{r}_1, \mathbf{r}_2)
  \right|_{\mathbf{r}_1 = \mathbf{r}_2 = \mathbf{r}_n}
\end{equation}
$$

### 2.4.1 Stress Tensor

$$
\begin{equation}
  \begin{split}
    \boldsymbol{\sigma}_{ij}(\mathbf{r}_n | \alpha, \beta)
    =&
    -\frac{1}{2} \alpha
    \left(
      \frac{\partial^2}{\partial r_i \partial r'_j} \gamma(\mathbf{r}, \mathbf{r}')
      + \frac{\partial^2}{\partial r_j \partial r'_i} \gamma(\mathbf{r}, \mathbf{r}')
    \right)_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    & +\frac{1}{2} (1 - \alpha)
    \left(
      \frac{\partial^2}{\partial r_i \partial r_j} \gamma(\mathbf{r}, \mathbf{r})
      + \frac{\partial^2}{\partial r'_i \partial r'_j} \gamma(\mathbf{r}, \mathbf{r}')
    \right)_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    & - \frac{1}{2} \delta_{ij} \beta \nabla^2 \rho(\mathbf{r}_n)\\
    =&
    - \alpha
    \left.
      \frac{\partial^2}{\partial r_i \partial r'_j} \gamma(\mathbf{r}, \mathbf{r}')
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}
    + (1 - \alpha)
    \left.
      \frac{\partial^2}{\partial r_i \partial r_j} \gamma(\mathbf{r}, \mathbf{r})
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}
    - \frac{1}{2} \delta_{ij} \beta \nabla^2 \rho(\mathbf{r}_n)\\
  \end{split}
\end{equation}
$$

In [12]:
from gbasis.evals.stress_tensor import evaluate_stress_tensor

# evaluate stress tensor (α = 1 and β = 0) at one point using density matrix expressed w.r.t. atomic orbitals
stress_tensor_1_0_atomic = evaluate_stress_tensor(one_dm_atomic, basis, one_point)

# evaluate stress tensor (α = 0.5 and β = 1) at one point using density matrix expressed w.r.t. atomic orbitals
stress_tensor_point5_1_atomic = evaluate_stress_tensor(one_dm_atomic, basis, one_point, alpha=0.5, beta=1)

# evaluate stress tensor (α = 1 and β = 0) at one point using density matrix expressed w.r.t. molecular orbitals
stress_tensor_1_0_molecular = evaluate_stress_tensor(one_dm_molecular, basis, one_point, transform=transform)

print("Stress Tensor (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(stress_tensor_1_0_atomic)
print()
print("Stress Tensor (α = 0.5 and β = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(stress_tensor_point5_1_atomic)
print()
print("Stress Tensor (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(stress_tensor_1_0_molecular)

Stress Tensor (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[[-1.50109699 -2.15130977 -3.49963763]
  [-2.15130977 -4.06566937 -6.29627498]
  [-3.49963763 -6.29627498 -9.6457893 ]]]

Stress Tensor (α = 0.5 and β = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[[-25.73110268   2.05020775   2.38545362]
  [  2.05020775 -24.0083621    4.17452027]
  [  2.38545362   4.17452027 -21.30297803]]]

Stress Tensor (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[[[ -59.58614016 -119.56239624 -162.64305282]
  [-119.56239624 -241.11186102 -327.29082187]
  [-162.64305282 -327.29082187 -444.27438511]]]


### 2.4.2 Ehrenfest Force

Ehrenfest force is defined as the negative of the divergence of the stress tensor:

$$
\begin{equation}
  \hspace{-4em}
  \begin{split}
    F_{j}(\mathbf{r}_n | \alpha, \beta)
    =&
    - \sum_i \frac{\partial}{\partial r_i} \boldsymbol{\sigma}_{ij}\\
    =&
    \alpha
    \sum_i
    \left.
      \frac{\partial^3}{\partial r^2_i \partial r'_j} \gamma(\mathbf{r}, \mathbf{r}')
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}
    + \alpha
    \sum_i
    \left.
      \frac{\partial^3}{\partial r_i \partial r'_i \partial r'_j} \gamma(\mathbf{r}, \mathbf{r}')
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    &- (1 - \alpha)
    \sum_i
    \left.
      \frac{\partial^3}{\partial r^2_i \partial r_j} \gamma(\mathbf{r}, \mathbf{r})
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}
    - (1 - \alpha)
    \sum_i
    \left.
      \frac{\partial^3}{\partial r_i \partial r_j \partial r'_i} \gamma(\mathbf{r}, \mathbf{r})
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}
    + \frac{1}{2} \sum_i \delta_{ij} \beta
    \frac{\partial}{\partial r_i} \nabla^2 \rho(\mathbf{r}_n)\\
    =&
    \alpha
    \sum_i
    \left.
      \frac{\partial^3}{\partial r^2_i \partial r'_j} \gamma(\mathbf{r}, \mathbf{r}')
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    &- (1 - \alpha)
    \sum_i
    \left.
      \frac{\partial^3}{\partial r^2_i \partial r_j} \gamma(\mathbf{r}, \mathbf{r})
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}
    - (1 - 2\alpha)
    \sum_i
    \left.
      \frac{\partial^3}{\partial r_i \partial r_j \partial r'_i} \gamma(\mathbf{r}, \mathbf{r})
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}
    + \frac{1}{2} \sum_i \delta_{ij} \beta
    \frac{\partial}{\partial r_i} \nabla^2 \rho(\mathbf{r}_n)\\
  \end{split}
\end{equation}
$$

In [13]:
from gbasis.evals.stress_tensor import evaluate_ehrenfest_force

# evaluate Ehrenfest force (α = 1 and β = 0) at one point using density matrix expressed w.r.t. atomic orbitals
ehren_force_1_0_atomic = evaluate_ehrenfest_force(one_dm_atomic, basis, one_point)

# evaluate Ehrenfest force (α = 0.5 and β = 1) at one point using density matrix expressed w.r.t. atomic orbitals
ehren_force_point5_1_atomic = evaluate_ehrenfest_force(one_dm_atomic, basis, one_point, alpha=0.5, beta=1)

# evaluate Ehrenfest force (α = 1 and β = 0) at one point using density matrix expressed w.r.t. molecular orbitals
ehren_force_1_0_molecular = evaluate_ehrenfest_force(one_dm_molecular, basis, one_point, transform=transform)

print("Ehrenfest Force (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(ehren_force_1_0_atomic)
print()
print("Ehrenfest Force (α = 0.5 and β = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(ehren_force_point5_1_atomic)
print()
print("Ehrenfest Force (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(ehren_force_1_0_molecular)

Ehrenfest Force (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[-26.51107153 -45.70266719 -67.98968168]]

Ehrenfest Force (α = 0.5 and β = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[ -51.52632061  -89.91964629 -132.66800942]]

Ehrenfest Force (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[[-1314.22008243 -2339.75315262 -3075.87909323]]


### 2.4.3 Ehrenfest Hessian

$$
\begin{equation}
  \begin{split}
    H_{jk}(\mathbf{r}_n | \alpha, \beta)
    =&
    - \frac{\partial}{\partial r_k} F_j(\mathbf{r}_n | \alpha, \beta)\\
    =&
    \alpha
    \sum_i
    \left(
      \frac{\partial^4}{\partial r^2_i \partial r_k \partial r'_j} \gamma(\mathbf{r}, \mathbf{r}')
      +\frac{\partial^4}{\partial r^2_i \partial r'_j \partial r'_k} \gamma(\mathbf{r}, \mathbf{r}')
    \right)_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    &- (1 - \alpha)
    \sum_i
    \left(
      \frac{\partial^4}{\partial r^2_i \partial r_j \partial r_k} \gamma(\mathbf{r}, \mathbf{r})
      + \frac{\partial^4}{\partial r^2_i \partial r_j \partial r'_k} \gamma(\mathbf{r}, \mathbf{r})
    \right)_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    &- (1 - 2\alpha)
    \sum_i
    \left(
      \frac{\partial^4}{\partial r_i \partial r_j \partial r_k \partial r'_i} \gamma(\mathbf{r}, \mathbf{r})
      + \frac{\partial^4}{\partial r_i \partial r_j \partial r'_i \partial r'_k} \gamma(\mathbf{r}, \mathbf{r})
    \right)_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    &+ \frac{1}{2} \sum_i \delta_{ij} \beta
    \frac{\partial^2}{\partial r_i \partial r_k} \nabla^2 \rho(\mathbf{r}_n)\\
  \end{split}
\end{equation}
$$

In [14]:
from gbasis.evals.stress_tensor import evaluate_ehrenfest_hessian

# evaluate Ehrenfest Hessian (α = 1 and β = 0) at one point using density matrix expressed w.r.t. atomic orbitals
ehren_hess_1_0_atomic = evaluate_ehrenfest_hessian(one_dm_atomic, basis, one_point)

# evaluate Ehrenfest Hessian (α = 0.5 and β = 1) at one point using density matrix expressed w.r.t. atomic orbitals
ehren_hess_point5_1_atomic = evaluate_ehrenfest_hessian(one_dm_atomic, basis, one_point, alpha=0.5, beta=1)

# evaluate Ehrenfest Hessian (α = 1 and β = 0) at one point using density matrix expressed w.r.t. molecular orbitals
ehren_hess_1_0_molecular = evaluate_ehrenfest_hessian(one_dm_molecular, basis, one_point, transform=transform)

print("Ehrenfest Hessian (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(ehren_hess_1_0_atomic)
print()
print("Ehrenfest Hessian (α = 0.5 and β = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(ehren_hess_point5_1_atomic)
print()
print("Ehrenfest Hessian (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(ehren_hess_1_0_molecular)

Ehrenfest Hessian (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[[-32.99752919 139.01673775 199.86296432]
  [137.49234144 106.06133076 347.33446009]
  [196.97762135 348.24612957 384.32469864]]]

Ehrenfest Hessian (α = 0.5 and β = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[[[-83.37210687 246.82506953 354.44022542]
  [245.30067323 170.89842617 631.54343183]
  [351.55488245 632.45510132 678.58032649]]]

Ehrenfest Hessian (α = 1 and β = 0) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[[[-1532.40831373  7667.06636586  9506.2190626 ]
  [ 7503.88905373  6532.61010956 16813.21484291]
  [ 9392.42939228 17036.14492026 16131.88547665]]]


### 2.4.4 Positive-Definite Kinetic Energy Density

$$
\begin{equation}
  \begin{split}
    t_+ (\mathbf{r}_n)
    &= \frac{1}{2} \left.
      \nabla_{\mathbf{r}} \cdot \nabla_{\mathbf{r}'} \gamma(\mathbf{r}, \mathbf{r}')
    \right|_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
    &= \frac{1}{2} \left(
      \frac{\partial^2}{\partial x \partial x'} \gamma(\mathbf{r}, \mathbf{r}')
      + \frac{\partial^2}{\partial y \partial y'} \gamma(\mathbf{r}, \mathbf{r}')
      + \frac{\partial^2}{\partial z \partial z'} \gamma(\mathbf{r}, \mathbf{r}')
    \right)_{\mathbf{r} = \mathbf{r}' = \mathbf{r}_n}\\
  \end{split}
\end{equation}
$$

In [15]:
from gbasis.evals.density import evaluate_posdef_kinetic_energy_density

# evaluate positive-definite kinetic energy density at one point using density matrix 
# expressed w.r.t. atomic orbitals
pos_def_T_atomic = evaluate_posdef_kinetic_energy_density(one_dm_atomic, basis, one_point)

# evaluate positive-definite kinetic energy density at one point using density matrix 
# expressed w.r.t. molecular orbitals
pos_def_T_molecular = evaluate_posdef_kinetic_energy_density(one_dm_molecular, basis, one_point, transform)

print("Positive-Definite Kinetic Energy Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(pos_def_T_atomic)
print()
print("Positive-Definite Kinetic Energy Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(pos_def_T_molecular)

Positive-Definite Kinetic Energy Density Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[7.60627783]

Positive-Definite Kinetic Energy Density Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[372.48619314]


### 2.4.5 General Form of Kinetic Energy Density

$$
\begin{equation}
  t_{\alpha} (\mathbf{r}_n) = t_+(\mathbf{r}_n) + \alpha \nabla^2 \rho(\mathbf{r}_n)
\end{equation}
$$

In [16]:
from gbasis.evals.density import evaluate_general_kinetic_energy_density

# evaluate general form of kinetic energy density (α = 1) at one point using density matrix
# expressed w.r.t. atomic orbitals
general_T_1_atomic = evaluate_general_kinetic_energy_density(one_dm_atomic, basis, one_point, 1)

# evaluate general form of kinetic energy density (α = 0.5) at one point using density matrix
# expressed w.r.t. atomic orbitals
general_T_point5_atomic = evaluate_general_kinetic_energy_density(one_dm_atomic, basis, one_point, 0.5)

# evaluate general form of kinetic energy density (α = 1) at one point using density matrix
# expressed w.r.t. molecular orbitals
general_T_1_molecular = evaluate_general_kinetic_energy_density(one_dm_molecular, basis, one_point, 1, transform)

print("General Form of Kinetic Energy Density (α = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(general_T_1_atomic)
print()
print("General Form of Kinetic Energy Density (α = 0.5) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(general_T_point5_atomic)
print()
print("General Form of Kinetic Energy Density (α = 1) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(general_T_1_molecular)

General Form of Kinetic Energy Density (α = 1) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[52.27018755]

General Form of Kinetic Energy Density (α = 0.5) Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[29.93823269]

General Form of Kinetic Energy Density (α = 1) Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[2525.80009721]


# 3 Integrals

## 3.1 Overlap Integral

$$
\begin{equation}
  \label{eq:overlap}
  \int \phi_a (\mathbf{r}) \phi_b (\mathbf{r}) d\mathbf{r}
\end{equation}
$$

In [17]:
from gbasis.integrals.overlap import overlap_integral

# compute overlap of set of atomic orbitals
atomic_overlap = overlap_integral(basis)

# compute overlap of set of molecular orbitals
molecular_overlap = overlap_integral(basis, transform)

print("Shape of Overlap Integral for Set of Atomic Orbitals (Number of AOs, Number of AOs):")
print(atomic_overlap.shape)
print()
print("Shape of Overlap Integral for Set of Molecular Orbitals (Number of MOs, Number of MOs):")
print(molecular_overlap.shape)

Shape of Overlap Integral for Set of Atomic Orbitals (Number of AOs, Number of AOs):
(18, 18)

Shape of Overlap Integral for Set of Molecular Orbitals (Number of MOs, Number of MOs):
(14, 14)


### 3.1.1 Overlap Integral Between Two Different Basis Sets

Overlap integrals between two different basis sets are supported i.e.,

$$
\begin{equation}
  \label{eq:overlap}
  \int \phi_a (\mathbf{r}) \psi_b (\mathbf{r}) d\mathbf{r}
\end{equation}
$$

In [18]:
from gbasis.integrals.overlap_asymm import overlap_integral_asymmetric

# create an ANO-RCC basis in spherical coordinates for Be-C (10 basis functions total)
basis_dict_anorcc = parse_nwchem("data_anorcc.nwchem")
# NOTE: used HORTON's conversion factor for angstroms to bohr
Be_C_basis = make_contractions(basis_dict, ["Be", "C"], np.array([[0, 0, 0], [1.0 * 1.0 / 0.5291772083, 0, 0]]))

# compute overlap between two sets of atomic orbitals
atomic_atomic_overlap = overlap_integral_asymmetric(Be_C_basis, Be_C_basis)

# define a tranformation matrix to obtain 8 molecular orbitals from 10 atomic orbitals
Be_C_transform = np.random.rand(8, 10)

# compute overlap between set of molecular orbitals and set of atomic orbitals
molecular_atomic_overlap = overlap_integral_asymmetric(Be_C_basis, Be_C_basis, transform_one=Be_C_transform)

print("Shape of Overlap Integral for Two Sets of Atomic Orbitals (Number of AOs, Number of AOs):")
print(atomic_atomic_overlap.shape)
print()
print("Shape of Overlap Integral for Set of Molecular Orbitals and Set of Atomic Orbitals (Number of MOs, Number of AOs):")
print(molecular_atomic_overlap.shape)

Shape of Overlap Integral for Two Sets of Atomic Orbitals (Number of AOs, Number of AOs):
(10, 10)

Shape of Overlap Integral for Set of Molecular Orbitals and Set of Atomic Orbitals (Number of MOs, Number of AOs):
(8, 10)


## 3.2 Multipole Moment Integral

Multipole moment integral can be obtained for arbitrary moments.

$$
\begin{equation}
  \label{eq:multipole}
  \int \phi_a (\mathbf{r}) (x - X_C)^{c_x} (y - Y_C)^{c_y} (z - Z_C)^{c_z} \phi_b (\mathbf{r}) d\mathbf{r}
\end{equation}
$$

As an example, suppose the integral of the following moments is desired:

$$
\begin{equation}
  (x - 1.5)^2 (y - 2.5)^3 (z - 3.5)
\end{equation}
$$
$$
\begin{equation}
  (x - 1.5) (y - 2.5)^2 (z - 3.5)^3
\end{equation}
$$

In [19]:
from gbasis.integrals.moment import moment_integral

# compute moment of a set of atomic orbitals 
atomic_moment = moment_integral(basis, np.array([1.5, 2.5, 3.5]), np.array([[2, 3, 1], [1, 2, 3]]))

# compute moment of a set of molecular orbitals
molecular_moment = moment_integral(basis, np.array([1.5, 2.5, 3.5]), np.array([[2, 3, 1], [1, 2, 3]]), transform)

print("Shape of Moment for Set of Atomic Orbitals (Number of AOs, Number of AOs, Number of Sets of Moment Orders):")
print(atomic_moment.shape)
print()
print("Shape of Moment for Set of Molecular Orbitals (Number of MOs, Number of MOs, Number of Sets of Moment Orders):")
print(molecular_moment.shape)

Shape of Moment for Set of Atomic Orbitals (Number of AOs, Number of AOs, Number of Sets of Moment Orders):
(18, 18, 2)

Shape of Moment for Set of Molecular Orbitals (Number of MOs, Number of MOs, Number of Sets of Moment Orders):
(14, 14, 2)


## 3.3 Integrals Over Differential Operator

Integrals over arbitrary differential operator (for Cartesian coordinates) are
supported.

$$
\begin{equation}
  \int
  \phi_a(\mathbf{r}) \frac{\partial^{e+f+g}}{\partial x^e \partial y^f \partial z^g} \phi_b(\mathbf{r})
  d\mathbf{r}
\end{equation}
$$

### 3.3.1 Kinetic Energy Integral

$$
\begin{equation}
  \label{eq:kinetic_energy}
  \begin{split}
    \left< \hat{T} \right>
    &= \int \phi_a(\mathbf{r}) \left( -\frac{1}{2} \nabla^2 \right) \phi_b(\mathbf{r}) d\mathbf{r}\\
    &= -\frac{1}{2}
    \left(
      \int \phi_a(\mathbf{r}) \frac{\partial^2}{\partial x^2} \phi_b(\mathbf{r}) d\mathbf{r}
      + \int \phi_a(\mathbf{r}) \frac{\partial^2}{\partial y^2} \phi_b(\mathbf{r}) d\mathbf{r}
      + \int \phi_a(\mathbf{r}) \frac{\partial^2}{\partial z^2} \phi_b(\mathbf{r}) d\mathbf{r}
    \right)
  \end{split}
\end{equation}
$$

In [20]:
from gbasis.integrals.kinetic_energy import kinetic_energy_integral

# compute kinetic energy integral of a set of atomic orbitals
T_integral_atomic = kinetic_energy_integral(basis)

# compute kinetic energy integral of a set of molecular orbitals
T_integral_molecular = kinetic_energy_integral(basis, transform)

print("Shape of Kinetic Energy Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs):")
print(T_integral_atomic.shape)
print()
print("Shape of Kinetic Energy Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs):")
print(T_integral_molecular.shape)

Shape of Kinetic Energy Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs):
(18, 18)

Shape of Kinetic Energy Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs):
(14, 14)


### 3.3.2 Momentum Integral

$$
\begin{equation}
  \label{eq:momentum}
  \begin{split}
    \left< \hat{\mathbf{p}} \right>
    &= \int \phi_a(\mathbf{r}) \left( -i \nabla \right) \phi_b(\mathbf{r}) d\mathbf{r}\\
    &= -i
    \begin{bmatrix}
      \int \phi_a(\mathbf{r}) \frac{\partial}{\partial x} \phi_b(\mathbf{r}) d\mathbf{r}\\\\
      \int \phi_a(\mathbf{r}) \frac{\partial}{\partial y} \phi_b(\mathbf{r}) d\mathbf{r}\\\\
      \int \phi_a(\mathbf{r}) \frac{\partial}{\partial z} \phi_b(\mathbf{r}) d\mathbf{r}
    \end{bmatrix}
  \end{split}
\end{equation}
$$

In [21]:
from gbasis.integrals.momentum import momentum_integral

# compute momentum integral of a set of atomic orbitals
momentum_integral_atomic = momentum_integral(basis)

# compute momentum integral of a set of molecular orbitals
momentum_integral_molecular = momentum_integral(basis, transform)

print("Shape of Momentum Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs, 3):")
print(momentum_integral_atomic.shape)
print()
print("Shape of Momentum Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs, 3):")
print(momentum_integral_molecular.shape)

Shape of Momentum Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs, 3):
(18, 18, 3)

Shape of Momentum Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs, 3):
(14, 14, 3)


### 3.3.3 Angular Momentum Integral

$$
\begin{equation}
  \label{eq:angular_momentum}
  \begin{split}
    \left< \hat{\mathbf{L}} \right>
    &= \int \phi_a(\mathbf{r}) \left( -i \mathbf{r} \times \nabla \right) \phi_b(\mathbf{r}) d\mathbf{r}\\
    &= -i
    \begin{bmatrix}
      \int \phi_a(\mathbf{r}) y\frac{\partial}{\partial z} \phi_b(\mathbf{r}) d\mathbf{r}
      - \int \phi_a(\mathbf{r}) z\frac{\partial}{\partial y} \phi_b(\mathbf{r}) d\mathbf{r}\\\\
      \int \phi_a(\mathbf{r}) z\frac{\partial}{\partial x} \phi_b(\mathbf{r}) d\mathbf{r}
      - \int \phi_a(\mathbf{r}) x\frac{\partial}{\partial z} \phi_b(\mathbf{r}) d\mathbf{r}\\\\
      \int \phi_a(\mathbf{r}) x\frac{\partial}{\partial y} \phi_b(\mathbf{r}) d\mathbf{r}
      - \int \phi_a(\mathbf{r}) y\frac{\partial}{\partial x} \phi_b(\mathbf{r}) d\mathbf{r}\\\\
    \end{bmatrix}
  \end{split}
\end{equation}
$$

In [22]:
from gbasis.integrals.angular_momentum import angular_momentum_integral

# compute angular momentum integral of a set of atomic orbitals
ang_mom_integral_atomic = angular_momentum_integral(basis)

# compute angular momentum integral of a set of molecular orbitals
ang_mom_integral_molecular = angular_momentum_integral(basis, transform)

print("Shape of Angular Momentum Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs, 3):")
print(ang_mom_integral_atomic.shape)
print()
print("Shape of Angular Momentum Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs, 3):")
print(ang_mom_integral_molecular.shape)

Shape of Angular Momentum Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs, 3):
(18, 18, 3)

Shape of Angular Momentum Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs, 3):
(14, 14, 3)


## 3.4 Integral for Interaction with Point Charge

$$
\begin{equation}
  \label{eq:point_charge}
  \int \phi_a(\mathbf{r}) \frac{1}{|\mathbf{r} - \mathbf{R}_C|} \phi_b(\mathbf{r}) d\mathbf{r}
\end{equation}
$$

For example, suppose there are two point charges: $-3$ charge at $(0, 1, 2)$ and $+5$ charge
at $(3, 4, 6)$:

In [23]:
from gbasis.integrals.point_charge import point_charge_integral

# compute integral for interaction between these point charges and the set of atomic orbitals
interaction_atomic = point_charge_integral(basis, np.array([[0, 1, 2], [3, 4, 6]]), np.array([-3, 5]))

# compute integral for interaction between these point charges and the set of molecular orbitals
interaction_molecular = point_charge_integral(basis, np.array([[0, 1, 2], [3, 4, 6]]), np.array([-3, 5]), transform)

print("Shape of Integral for Interaction Between Point Charges and Set of Atomic Orbitals (Number of AOs, Number of AOs, Number of Point Charges):")
print(interaction_atomic.shape)
print()
print("Shape of Integral for Interaction Between Point Charges and Set of Molecular Orbitals (Number of MOs, Number of MOs, Number of Point Charges):")
print(interaction_molecular.shape)

Shape of Integral for Interaction Between Point Charges and Set of Atomic Orbitals (Number of AOs, Number of AOs, Number of Point Charges):
(18, 18, 2)

Shape of Integral for Interaction Between Point Charges and Set of Molecular Orbitals (Number of MOs, Number of MOs, Number of Point Charges):
(14, 14, 2)


### 3.4.1 Nuclear-Electron Attraction Integral

$$
\begin{equation}
  \label{eq:nuclear_electron_attraction}
  \int \phi_a(\mathbf{r}) \frac{-Z_c}{|\mathbf{r} - \mathbf{R}_C|} \phi_b(\mathbf{r}) d\mathbf{r}
  =
  -Z_C \int \phi_a(\mathbf{r}) \frac{1}{|\mathbf{r} - \mathbf{R}_C|} \phi_b(\mathbf{r}) d\mathbf{r}
\end{equation}
$$

For example, suppose there are two nuclei: He at $(0, 1, 2)$ and Al at $(3, 4, 6)$:

In [24]:
from gbasis.integrals.nuclear_electron_attraction import nuclear_electron_attraction_integral

# compute nuclear-electron attraction integral of set of atomic orbitals
Vne_atomic = nuclear_electron_attraction_integral(basis, np.array([[0, 1, 2], [3, 4, 6]]), np.array([2, 13]))

# compute nuclear-electron attraction integral of set of molecular orbitals
Vne_molecular = nuclear_electron_attraction_integral(basis, 
                                                     np.array([[0, 1, 2], [3, 4, 6]]), 
                                                     np.array([2, 13]), 
                                                     transform)

print("Shape of Nuclear-Electron Attraction Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs):")
print(Vne_atomic.shape)
print()
print("Shape of Nuclear-Electron Attraction Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs):")
print(Vne_molecular.shape)

Shape of Nuclear-Electron Attraction Integral of Set of Atomic Orbitals (Number of AOs, Number of AOs):
(18, 18)

Shape of Nuclear-Electron Attraction Integral of Set of Molecular Orbitals (Number of MOs, Number of MOs):
(14, 14)


### 3.4.2 Electrostatic Potential

$$
\begin{equation}
  \label{eq:nuclear_electron_attraction}
  \hspace{-3em}
  - \left(
    - \sum_A \frac{Z_A}{|\mathbf{R}_C - \mathbf{R}_A|}
    + \sum_{ab} \gamma_{ab} \int \phi_a(\mathbf{r}) \frac{-1}{|\mathbf{r} - \mathbf{R}_C|} \phi_b(\mathbf{r}) d\mathbf{r}
  \right)
  =
  \sum_A \frac{Z_A}{|\mathbf{R}_C - \mathbf{R}_A|}
  - \sum_{ab} \gamma_{ab} \int \phi_a(\mathbf{r}) \frac{1}{|\mathbf{r} - \mathbf{R}_C|} \phi_b(\mathbf{r}) d\mathbf{r}
\end{equation}
$$

For example, suppose there are two nuclei, He at $(0, 1, 2)$ and Al at $(3, 4, 6)$, the electrostatic potential is measured at
points $(0.5, 1.5, 2.5)$ and $(2.5, 3.5, 5.5)$, and the one-electron density
matrix is known:

In [25]:
from gbasis.evals.electrostatic_potential import electrostatic_potential

# compute electrostatic potential using density matrix expressed w.r.t. atomic orbitals
ESP_atomic = electrostatic_potential(basis, 
                                     one_dm_atomic, 
                                     np.array([[0.5, 1.5, 2.5], [2.5, 3.5, 5.5]]), 
                                     np.array([[0, 1, 2], [3, 4, 6]]), 
                                     np.array([2, 13]))

# compute electrostatic potential using density matrix expressed w.r.t. molecular orbitals
ESP_molecular = electrostatic_potential(basis, 
                                        one_dm_molecular, 
                                        np.array([[0.5, 1.5, 2.5], [2.5, 3.5, 5.5]]), 
                                        np.array([[0, 1, 2], [3, 4, 6]]), 
                                        np.array([2, 13]),
                                        transform)

print("Electrostatic Potential Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:")
print(ESP_atomic)
print()
print("Electrostatic Potential Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:")
print(ESP_molecular)

Electrostatic Potential Evaluated with Density Matrix Expressed w.r.t. Atomic Orbitals:
[-4.52728449 11.68296016]

Electrostatic Potential Evaluated with Density Matrix Expressed w.r.t. Molecular Orbitals:
[-461.83163627 -169.93340194]


## 3.5 Electron-Electron Repulsion Integral

In the Chemists' notation,

$$
\begin{equation}
  \label{eq:elec_repulsion}
  \int \phi^*_a(\mathbf{r}_1) \phi_b(\mathbf{r}_1)
  \frac{1}{|\mathbf{r}_1 - \mathbf{r}_2|}
  \phi^*_c(\mathbf{r}_2) \phi_d(\mathbf{r}_2) d\mathbf{r}
\end{equation}
$$

In the Physicists' notation,

$$
\begin{equation}
  \label{eq:elec_repulsion_phys}
  \int \phi^*_a(\mathbf{r}_1) \phi^*_b(\mathbf{r}_2)
  \frac{1}{|\mathbf{r}_1 - \mathbf{r}_2|}
  \phi_c(\mathbf{r}_1) \phi_d(\mathbf{r}_2) d\mathbf{r}
\end{equation}
$$

It may be useful to note that though both conventions are supported at the higher level, lower level code uses the Chemists’ notation.

In [26]:
from gbasis.integrals.electron_repulsion import electron_repulsion_integral

# compute electron-electron repulsion integral of a set of atomic orbitals in Physicists' notation
Vee_atomic_physicist = electron_repulsion_integral(basis)

# compute electron-electron repulsion integral of a set of molecular orbitals in Physicists' notation
Vee_molecular_physicist = electron_repulsion_integral(basis, transform)

# compute electron-electron repulsion integral of a set of molecular orbitals in Chemists' notation
Vee_molecular_chemist = electron_repulsion_integral(basis, transform, notation='chemist')

print("Shape of Electron-Electron Repulsion Integral of a Set of Atomic Orbitals in Physicists' Notation (Number of AOs, Number of AOs, Number of AOs, Number of AOs):")
print(Vee_atomic_physicist.shape)
print()
print("Shape of Electron-Electron Repulsion Integral of a Set of Molecular Orbitals in Physicists' Notation (Number of MOs, Number of MOs, Number of MOs, Number of MOs):")
print(Vee_molecular_physicist.shape)
print()
print("Shape of Electron-Electron Repulsion Integral of a Set of Molecular Orbitals in Chemists' Notation (Number of MOs, Number of MOs, Number of MOs, Number of MOs):")
print(Vee_molecular_chemist.shape)

Shape of Electron-Electron Repulsion Integral of a Set of Atomic Orbitals in Physicists' Notation (Number of AOs, Number of AOs, Number of AOs, Number of AOs):
(18, 18, 18, 18)

Shape of Electron-Electron Repulsion Integral of a Set of Molecular Orbitals in Physicists' Notation (Number of MOs, Number of MOs, Number of MOs, Number of MOs):
(14, 14, 14, 14)

Shape of Electron-Electron Repulsion Integral of a Set of Molecular Orbitals in Chemists' Notation (Number of MOs, Number of MOs, Number of MOs, Number of MOs):
(14, 14, 14, 14)
